### ISSUE TITLE
Ajustar carrossel dos destaque da home no mobile

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/malocadragao#10]
![imagem da pagina 2016-04-27 - 10 42 10](https://cloud.githubusercontent.com/assets/69956/14855012/67077e02-0c68-11e6-8cb3-a057a9145067.png)

A imagem de destaque aparece menor que as demais.

**Comment by nicolavieira** [comment]
@bruno sabe me dizer em qual dispositivo isso foi testado? eu testei no emulador do navegador e está ok

**Comment by brunosmartin** [comment]
@ariadnemelo testei no emulardor do firefox, mas não testei em celular de verdade

**Comment by nicolavieira** [comment]
@bruno testei no firefox no meu celular e está ok 
![photo844020035431278530](https://cloud.githubusercontent.com/assets/2034550/14891246/2f88bb92-0d3c-11e6-8976-580cec0419e6.jpg)
