### ISSUE TITLE
Substituir "Virada Cultural" por "Maloca Dragão"  e  "Minha Virada" por "Minha Maloca" no mobile

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/malocadragao#14]
![screenshot_2016-04-27-15-56-06](https://cloud.githubusercontent.com/assets/14170372/14864698/6bcd9ca4-0c91-11e6-8915-4a1c658afe34.png)

![screenshot_2016-04-27-15-55-17](https://cloud.githubusercontent.com/assets/14170372/14864693/6733ce02-0c91-11e6-874a-ca2b14d41d55.png)

**Comment by Andreqlp** [comment]
Só para lembrar

**Comment by brunosmartin** [comment]
Foi resolvido na versão nova, não?
Em 29 de abr de 2016 11:20, "Andreqlp" notifications@github.com escreveu:
