### ISSUE TITLE
Abaixo do título do evento, parece que falta um ícone

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/malocadragao#7]
![captura de tela de 2016-04-27 10-45-49](https://cloud.githubusercontent.com/assets/69956/14854246/58dd9292-0c65-11e6-92e6-6ed92bafd4e0.png)

http://malocadragao.org.br/2016/programacao/atracao/##72

**Comment by nicolavieira** [comment]
@bruno essa depende da #8 pois o ícone é o mesmo
