### ISSUE TITLE
Adicionar favicon, e colocar este ícone no item de menu "A Maloca"

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/malocadragao#8]
![favicom 700px](https://cloud.githubusercontent.com/assets/69956/14854313/a9b7388a-0c65-11e6-97ee-72c2abaeeb67.jpg)

O ícone atual da primeira entrada do menu é da Virada BH! ;-\

**Comment by nicolavieira** [comment]
@bruno eu preciso do arquivo vetorial para conseguir mudar o ícone

**Comment by Andreqlp** [comment]
No formato SVG
https://drive.google.com/open?id=0B4Q7Y_cuhmVKTW1XMWstZlBCNTg

No formato EPS
https://drive.google.com/open?id=0B4Q7Y_cuhmVKX2Vtd0ZrbVZOQmc

**Comment by nicolavieira** [comment]
@Andreqlp acho que eu não tenho permissão pra ver o arquivo, se quiser pode me mandar por email mesmo, ariadne@hacklab.com.br

valeu!

**Comment by Andreqlp** [comment]
anexo

2016-04-27 16:15 GMT-03:00 Ariadne Melo notifications@github.com:

> @Andreqlp https://github.com/Andreqlp acho que eu não tenho permissão
> pra ver o arquivo, se quiser pode me mandar por email mesmo,
> ariadne@hacklab.com.br
> 
> valeu!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabr/malocadragao/issues/8#issuecomment-215197836

## 

André Quintino Lopes
(85) 98834-8813

**Comment by nicolavieira** [comment]
acabei de mudar o ícone do menu e o favicon aparentemente já estava funcionando, posso fechar essa issue? @brunosmartin

**Comment by Andreqlp** [comment]
pode sim

2016-04-27 16:45 GMT-03:00 Ariadne Melo notifications@github.com:

> acabei de mudar o ícone do menu e o favicon aparentemente já estava
> funcionando, posso fechar essa issue?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabr/malocadragao/issues/8#issuecomment-215206429

## 

André Quintino Lopes
(85) 98834-8813
