### ISSUE TITLE
Melhorar leiaute da programação no mobile

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/malocadragao#9]
![imagem da pagina 2016-04-27 - 10 42 55](https://cloud.githubusercontent.com/assets/69956/14854366/e3673dfa-0c65-11e6-9e43-e50f273ae022.png)

Colocar o Horário em baixo do evento e se necessário diminuir um pouco a fonte.

A ideia geral é dar "um tapa". Se precisar, pede ajdua pra o Luis

**Comment by nicolavieira** [comment]
@bruno @rafaelchavesfreitas a programação não está carregando no meu ambiente

**Comment by nicolavieira** [comment]
falta ajustar o layout na visualização por horário e por atração

**Comment by nicolavieira** [comment]
acho que agora foi, @brunosmartin pode olhar depois por favor?
